program: run_classification.py
name: distilbert_sweep
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  model_name:
    value: distilbert/distilbert-base-uncased
  dataset_name:
    values: MAdAiLab/amazon-attrprompt
  text_column_name:
    value: text
  label_column_name:
    value: label
  shuffle_train_dataset:
    value: true
  do_train:
    value: true
  do_eval:
    value: true
  do_predict:
    value: true
  max_seq_length:
    value: 512
  evaluation_strategy:
    value: steps
  eval_steps:
    value: 50
  per_device_train_batch_size:
    values: [8, 16, 32, 64]
  per_device_eval_batch_size:
    value: 32
  optim:
    value: adamw_torch
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  lr_scheduler_type:
    value: linear
  num_train_epochs:
    values: [3, 4, 5]
  logging_strategy:
    value: steps
  logging_steps:
    value: 10
  overwrite_output_dir:
    value: true
  output_dir:
    value: ./sweep_results
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 5
command:
  - ${env}
  - python3
  - ${program}
  - ${args}